Demo Index
----------

link:ejb-remote.asciidoc[ejb remote entry]



JBoss-as-7 & JBoss-eap-6 JNDI syntax:
-------------------------------------
* The JNDI lookup name for a stateless session bean has the syntax of: *ejb:<appName>/<moduleName>/<distinctName>/<beanName>!<viewClassName>*

* The JNDI lookup name for a stateful session bean has the syntax of: *ejb:<appName>/<moduleName>/<distinctName>/<beanName>!<viewClassName>?stateful*

. *<appName>* The application name is the name of the EAR that the EJB is deployed in (without the .ear).  If the EJB JAR is not deployed in an EAR then this is blank.  The app name can also be specified in the EAR's application.xml

. *<moduleName>* By the default the module name is the name of the EJB JAR file (without the .jar suffix).  The module name might be overridden in the ejb-jar.xml

. *<distinctName>* AS7 allows each deployment to have an (optional) distinct name. This example does not use this so leave it blank.

. *<beanName>* The name of the session been to be invoked.

. *<viewClassName>* The fully qualified classname of the remote interface.  Must include the whole package name.
