Demo entry
----------

link:ejb-remote.asciidoc[EJB remote demo entry]

link:ejb-in-war.asciidoc[EJB war test demo entry]

link:ejb-in-ear.asciidoc[EJB ear test demo entry]

link:ejb-security.asciidoc[EJB security demo entry]

link:ejb-singleton.asciidoc[EJB singleton demo entry]

link:ejb-mdb.asciidoc[EJB mdb demo entry]

link:ejb-cmt.asciidoc[EJB cmt demo entry]


JBoss-as-7 & JBoss-eap-6 JNDI lookup name syntax:
-------------------------------------------------
* stateless session bean: *ejb:<appName>/<moduleName>/<distinctName>/<beanName>!<viewClassName>*

* stateful session bean : *ejb:<appName>/<moduleName>/<distinctName>/<beanName>!<viewClassName>?stateful*

. *<appName>* The application name is the name of the EAR that the EJB is deployed in (without the .ear).  If the EJB JAR is not deployed in an EAR then this is blank.  The app name can also be specified in the EAR's application.xml

. *<moduleName>* By the default the module name is the name of the EJB JAR file (without the .jar suffix).  The module name might be overridden in the ejb-jar.xml

. *<distinctName>* AS7 allows each deployment to have an (optional) distinct name. This example does not use this so leave it blank.

. *<beanName>* The name of the session been to be invoked.

. *<viewClassName>* The fully qualified classname of the remote interface.  Must include the whole package name.



Install and Configure the PostgreSQL Database
----------------------------------------------

1. Install PostgreSQL
+++++++++++++++++++++

* Open a Terminal window and enter the following command:
----
yum install postgresql-server
----

* Use the following command check the installation result:
----
rpm -qa | grep postgres*
----

2. Set a password for the postgres user
+++++++++++++++++++++++++++++++++++++++

* the installation creates a user named postgres, change the password of User postgres, we only need login as root user enter the following user:
----
passwd postgres
----

* enter <passwd> twice for setting the password

* login as postgres by enter the command:
----
su - postgres
----



